---
name: Deploy mdBook to GitHub Pages

"on":
    push:
        branches:
            - main
    pull_request:

permissions:
    pages: write
    contents: write
jobs:
    deploy_book:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        env:
            MDBOOK_CONTAINER_VERSION: "0.5.0"
        steps:
            - uses: actions/checkout@v6

            - name: Build book in docker
              run: docker run --rm --mount "type=bind,src=$(pwd)/docs,target=/book" --mount "type=bind,src=$(pwd)/README.md,target=/README.md" ghcr.io/peaceiris/mdbook:v${MDBOOK_CONTAINER_VERSION} build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: book
                  path: ./docs/book
                  if-no-files-found: error
                  retention-days: 1
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/book
